### ISSUE TITLE
Scaffolding start error

### ISSUE THREAD

**Issue by gouych** [eclipse-theia/generator-theia-extension#170]
### Bug Description:
I use the widget option of scaffolding to create a project, but it fails to run on the desktop

### Steps to Reproduce:

1.yo theia-extension -t 1.34.4
2.I also added "main": "src-gen/frontend/electron-main.js" to electron-app/package.json
3.yarn watch && yarn start:electron
[
![image](https://github.com/eclipse-theia/theia/assets/43327905/bd1f02d2-fa78-4b38-9a64-644e52c738a9)
](url)

### Additional Information

- Operating System: macos
- Theia Version: 1.34.4

**Comment by msujew** [comment]
@vince-fugnitto The issue seems to be about the latest community release (1.34.4), using the main entry you point out won't work.

@gouych Can you try the latest Theia release (1.39.0) as well? Just to narrow down whether it's an issue related to the community release or a general one.

**Comment by gouych** [comment]
Everything works fine with the latest version.
Is there a solution for version 1.34.4.

**Comment by jfaltermeier** [comment]
I am seeing issues with 1.39 in the electron-app as well, using the hello world template and the 0.1.35 generator. 
For me either 
changing `prepare` to rebuild before the actual build (`"prepare": "theia rebuild:electron && theia build --mode development",`)
or
adding
`"main": "src-gen/backend/electron-main.js",`
works. 

Otherwise starting the electron app fails with `Error: node-loader: Error: Module did not self-register:` errors.

**Comment by vince-fugnitto** [comment]
Fixed by https://github.com/eclipse-theia/generator-theia-extension/pull/173.
